name: conditionals

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  check-conditions:
    runs-on: ubuntu-latest
    steps:
      - name: Branch Specific Task
        if: github.ref == 'refs/heads/main'
        run: echo "This step only runs on the main branch."

      - name: Experimental Task
        continue-on-error: true
        run: |
          echo "Running a task that might fail..."
          exit 1

      - name: Normal Follow-up Tasks
        run: echo "This runs because the previous step had continue-on-error."

      - name: Critical Execution Task
        run: |
          echo "Forcing a real failure to test the next step..."
          exit 1

      - name: Error Handling Task
        if: failure()
        run: echo "This step only runs because a previous step failed."

  on_pull:
    # This job only runs if the event triggering the workflow is a pull_request
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Pull Only Tasks
        run: echo "Only Runs When Pull event is happening"
