# This is the workflow of task 2 of day 41 on cron job

name: day41-schedule 

on:
    schedule:
        - cron: 0 0 * *  # Runs at 00:00 every day

jobs:
    scheduler:
        runs-on: ubuntu-latest
        steps:
            - name: Runnin Cron Job
              run: echo "Running daily schedule"
