# This is the workflow in which we github runner

name: github runner

on:
    workflow_dispatch:
    # push:
    #     branches: [main]

jobs:
    github-runner:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix: 
                os: [ubuntu-latest , windows-latest , macos-latest]

        # This forces Windows to use Bash, allowing universal commands
        defaults:
          run:
            shell: bash
        
        steps:
            - name: Print runner information
              run: |
                echo "OS name : $RUNNER_OS"
                echo "Hostname : $(hostname)"
                echo "Current user : $(whoami)"
                




