# This workflow greets

name: hello

on:
    push:
        branches: [main]


jobs:
    greet:
        runs-on: ubuntu-latest
        env:
            TZ: Asia/Kolkata # This will print time in IST
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Greet User
              run: echo  "Hello from GitHub Actions!"

            - name: Print the current date and time
              run: date

            - name: Print the name of the branch that triggered the run
              run: echo "This is the name of the branch - ${{ github.ref_name }}"

            - name: List the files in the repo
              run: ls -R

            - name: Print the runner's operating system
              run: echo "The runner OS is ${{ runner.os }}"

            - name: Running wrong command 
              #run: suda apt-get update # --> instead of sudo i wrote suda
              run: sudo apt-get update # --> fixed command 
            