# This workflow that reads it and prints: The secret is set: true (never print the actual value)  

name : secret check

on:
    workflow_dispatch: 
    # push:
    #     branches: [main]

jobs:
    secret-check:
        runs-on: ubuntu-latest
        steps:
            - name: Check if secret is set
              run: |
                if [ -n "${{ secrets.MY_SECRET_MESSAGE }}" ]; then
                    echo "The secret is set: true"
                else
                    echo "The secret is set: false"
                fi
            - name: Print secret
              run: echo "The secret message is :" ${{ secrets.MY_SECRET_MESSAGE }}