# This workflow uses self-hosted runner 

name: self hosted runner

on:
    push:
        branches: [main]

jobs:
    self-hosted-runner:
        runs-on: [self-hosted , my-linux-server]

        steps:
            # - name: Print the hostname of the machine 
            #   run:  "OS name : ${{ runner.os }}"

            # - name: Print the working directory 
            #   run: Working directory $(pwd)
            
            # - name: Create a file
            #   run: touch test.md
              - name: Checking following information about self-hosted runner
                run: |
                    echo "Hostname: $HOSTNAME"
                    echo "Working directory: $PWD"
                    echo "Namaste github" > namaste.txt
            
        