# This workflow uses a labeled self-hosted runner 

name: self hosted runner

on:
    workflow_dispatch:
    # push:
    #     branches: [main]

jobs:
    self-hosted-runner:
        # Changed to target your specific label
        runs-on: [self-hosted, my-linux-runner]

        steps:
            - name: Checking following information about self-hosted runner
              run: |
                  echo "Hostname: $HOSTNAME"
                  echo "Working directory: $PWD"
                  echo "Namaste github" > namaste.txt
