# This workflow contains parrallel and dependent jobs 

name: smart pipeline 

on:
    push:
        branches:
            - '**'


jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Runs Lint Job
              run: echo "This step is Lint step"

    test:
        runs-on: ubuntu-latest
        steps:
            - name: Runs Test Job
              run: echo "This step is Test step"

    summary:
        needs: [lint , test]
        runs-on: ubuntu-latest
        steps:
            - name: Print pushed branch name
              run: echo "Branch - ${{ github.ref_name }}"

            - name: Print commit message 
              run:  echo "Commit Message - ${{ github.event.head_commit.message }}"

    
    
